version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./mysite:/mysite
    command: >
      sh -c "python3 manage.py wait_for_db &&
             python3 manage.py migrate &&
             python3 manage.py initialize_db_values &&
             python3 manage.py runserver 0.0.0.0:8000"

    env_file:
      - ./.env
    depends_on:
      - db
      - redis

  db:
    build:
      context: ./
      dockerfile: db.Dockerfile
    ports:
      - "5433:5432"
    env_file:
      - ./.env
    volumes: 
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:alpine
volumes:
  pgdata: