# Generated by Django 4.1 on 2022-08-11 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provience',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('provienceId', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated_epoch', models.IntegerField()),
                ('temp_c', models.DecimalField(decimal_places=1, max_digits=2)),
                ('feelslike_c', models.DecimalField(decimal_places=1, max_digits=2)),
                ('condition_text', models.CharField(max_length=1000)),
                ('condition_icon', models.CharField(max_length=1000)),
                ('wind_kph', models.DecimalField(decimal_places=1, max_digits=3)),
                ('wind_dir', models.CharField(max_length=100)),
                ('humidity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('provience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.provience')),
                ('weather', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='weather.weather')),
            ],
        ),
        migrations.AddField(
            model_name='provience',
            name='weather',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='weather.weather'),
        ),
    ]
