# Generated by Django 4.1 on 2022-08-11 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provience',
            name='weather',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='weather.weather'),
        ),
        migrations.AlterField(
            model_name='town',
            name='weather',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='weather.weather'),
        ),
    ]
