# Generated by Django 4.1 on 2022-08-12 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_alter_weather_feelslike_c_alter_weather_temp_c_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provience',
            name='weather',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='weather.weather'),
        ),
        migrations.AlterField(
            model_name='town',
            name='weather',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='weather.weather'),
        ),
    ]
